server.port=8080
spring.application.name=hotel-candelaria

# ===== CONEXION A SQL SERVER con usuario sa =====
# Sin autenticacion de Windows (sin el .dll problem)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hotel_candelaria;trustServerCertificate=true;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=hoteluser
spring.datasource.password=Kenny2024

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
