# Puerto dinámico obligado para Render
server.port=${PORT:10000}

# Conexión a la Base de Datos usando tus Variables de Entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate y Dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Evitar que Hikari aborte el inicio si tarda en conectar
spring.datasource.hikari.initialization-fail-timeout=-1