spring.datasource.url=jdbc:postgresql://ep-autumn-flower-at3zk7gw.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ikhPF03mxCnT
spring.datasource.driver-class-name=org.postgresql.Driver

# Esto hace que Hibernate cree las tablas automáticamente en Neon apenas arranque en Render
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tiempo de espera extendido para evitar caídas por inicio lento
spring.datasource.hikari.connection-timeout=40000